# jaffle_shop:
#   target: dev
#   outputs:
#     dev:
#       type: postgres
#       host: db.bit.io
#       user: sungwonchung3
#       password: "{{ env_var('DB_PASS') }}"
#       port: 5432
#       dbname: sungwonchung3/constraints
#       schema: dbt_sung_a
#       threads: 24
#       connect_timeout: 10 # default 10 seconds
#     prod:
#       type: postgres
#       host: db.bit.io
#       user: sungwonchung3
#       password: "{{ env_var('DB_PASS') }}"
#       port: 5432
#       dbname: sungwonchung3/constraints
#       schema: dbt_sung_prod
#       threads: 24
#       connect_timeout: 10 # default 10 seconds

 jaffle_shop:
   target: databricks_job
   outputs:
     databricks_job:
      type: databricks
      method: http
      schema: dbt_test
      host: dbc-86f1e3fd-a558.cloud.databricks.com
      http_path: /sql/1.0/warehouses/a448cdf68a480e7b
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
