# version: 2

# models:
#   - name: constraints_example
#     docs:
#       node_color: black
#     config:
#       contract: false
#     columns:
#       - name: id
#         data_type: int
#         description: hello
#         constraints: 
#           - not null
#         constraints_check: (id > 0)
#         tests:
#           - unique
#       - name: color
#         data_type: text
#       - name: date_day
#         data_type: date