version: 2

groups:
  - name: finance
    owner:
      # 'name' or 'email' is required; additional properties allowed
      email: finance@team.com
      slack: finance-data
      github: finance-data-team

models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
    access: public
    group: finance
    config:
      contract:
        enforced: true
    latest_version: 2
    versions:
      - v: 2
        columns:
          - include: "*"
            exclude:
              - number_of_orders # this is the breaking change!
      - v: 1
        defined_in: customers
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        data_type: integer
        constraints:
          - type: not_null
        tests:
          - unique
          - not_null

      - name: first_name
        description: Customer's first name. PII.
        data_type: text

      - name: last_name
        description: Customer's last name. PII.
        data_type: text

      - name: first_order
        description: Date (UTC) of a customer's first order
        data_type: date

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order
        data_type: date

      - name: number_of_orders
        description: Count of the number of orders a customer has placed
        data_type: bigint

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders
        data_type: bigint

  - name: orders
    description: This table has basic information about orders, as well as some derived facts based on payments

    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - not_null

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card
        tests:
          - not_null

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon
        tests:
          - not_null

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer
        tests:
          - not_null

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
        tests:
          - not_null

semantic_models:
  - name: semantic_customers
    description: The semantic representation of the `customers` model
    model: ref('customers')
    entities:
      - name: customer
        type: primary
        expr: customer_id
    dimensions:
      - name: first_order
        type: time
      - name: most_recent_order
        type: time
    measures:
      - name: number_of_orders
        agg: sum
      - name: total_order_amount
        agg: sum
  - name: semantic_orders
    description: The semantic representation of the `orders` model
    model: ref('orders')
    entities:
      - name: order
        type: primary
        expr: order_id
      - name: customer
        type: foreign
        expr: customer_id
    dimensions:
      - name: order_date
        type: time
      - name: status
        type: categorical
    measures:
      - name: amount
        agg: sum
      - name: credit_card_amount
        agg: sum
      - name: coupon_amount
        agg: sum
      - name: bank_transfer_amount
        agg: sum
      - name: gift_card_amount
        agg: sum
metrics:
  - name: returned_amount
    label: Returned Amount
    type: simple
    type_params:
      measure:
        name: amount
        filter: status = 'return_pending'
  - name: returned_percent
    label: Returned Percent
    type: ratio
    type_params:
      numerator:
        name: amount
        filter: status = 'return_pending'
      denominator: amount
  - name: gift_card_amount
    label: Gift Card Amount
    type: simple
    type_params:
      measure: gift_card_amount
  - name: amount
    label: Amount
    type: simple
    type_params:
      measure: amount
  - name: non_gift_card_amount
    label: Non Gift Card Amount
    type: derived
    type_params:
      expr: amount - gift_card_amount
      metrics:
        - amount
        - gift_card_amount
